# Generated by Django 2.2 on 2020-02-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='contact_date',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='user_id',
        ),
    ]
