# Generated by Django 2.2 on 2020-02-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200205_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
